server.port: 8082

spring.application.name: ottm-svc1
spring.output.ansi.enabled: always

spring.microtx.lra:
  coordinator-url: http://localhost:9000/api/v1/lra-coordinator
  propagation-active: true
  participant-url: http://localhost:8082
  headers-propagation-prefix: { x-b3-, oracle-tmm-, authorization, refresh- }

svc1-sbu1.service.url: http://localhost:9011/svc-1/api/new

logging.level:
  com.kb: DEBUG