server.port: 9011

spring.application.name: ottm-svc1-sub1
spring.output.ansi.enabled: always

spring.microtx.lra:
  coordinator-url: http://localhost:9000/api/v1/lra-coordinator
  propagation-active: true
  participant-url: http://localhost:9011
  headers-propagation-prefix: { x-b3-, oracle-tmm-, authorization, refresh- }

logging.level:
  root: DEBUG
  com.kb: DEBUG