server.port: 8083

spring.application.name: ottm-svc2
spring.output.ansi.enabled: always

spring.microtx.lra:
  coordinator-url: ${SPRING_MICROTX_LRA_COORDINATOR_URL}
  propagation-active: true
  participant-url: ${SPRING_MICROTX_LRA_PARTICIPANT_URL}
  headers-propagation-prefix: { x-b3-, oracle-tmm-, authorization, refresh- }

logging.level:
  com.kb: DEBUG